OPENAI_API_KEY = "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"  # Replace with your actual OpenAI key
